export const FETCH_TYPES_POKEMONS_REQUEST = 'FETCH_TYPES_POKEMONS_REQUEST';
export const FETCH_TYPES_POKEMONS_SUCCESS = 'FETCH_TYPES_POKEMONS_SUCCESS';
export const FETCH_TYPES_POKEMONS_FAILURE = 'FETCH_TYPES_POKEMONS_FAILURE';